<a href="https://colab.research.google.com/github/Mohittrathee/Mullitiple_disease_prediction-using-ml/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
scaler=torch.tensor(9)
print(scaler)
print(scaler.dtype)
scaler.ndim


tensor(9)
torch.int64


0

In [5]:
scaler.item()

9

In [6]:
vector=torch.tensor([1,2,3])
print(vector)
print(vector.dtype)
vector.shape

tensor([1, 2, 3])
torch.int64


torch.Size([3])

In [7]:
vector.ndim

1

In [8]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix)
matrix.ndim


tensor([[1, 2, 3],
        [4, 5, 6]])


2

In [9]:
matrix.shape

torch.Size([2, 3])

In [10]:
tensor=torch.tensor([[[[1,2,3,4],
                      [4,5,6,7],
                      [7,8,9,0]]]])
tensor

tensor([[[[1, 2, 3, 4],
          [4, 5, 6, 7],
          [7, 8, 9, 0]]]])

In [11]:
tensor.shape

torch.Size([1, 1, 3, 4])

In [12]:
tensor.ndim

4

In [13]:
random_tensor=torch.rand(2,3,4)
random_tensor

tensor([[[0.8483, 0.8739, 0.2418, 0.0122],
         [0.3921, 0.3839, 0.9314, 0.2057],
         [0.6077, 0.8299, 0.6524, 0.2827]],

        [[0.9428, 0.2414, 0.4972, 0.6136],
         [0.7175, 0.9840, 0.6363, 0.0698],
         [0.3269, 0.6352, 0.7032, 0.2390]]])

In [14]:
random_image_size_tensor=torch.rand(size=(224,224,4))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 4]), 3)

In [15]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
arranje=torch.arange(0,11,1)
arranje

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
zeroes=torch.zeros_like(input=arranje)
zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
float_32_tensor=torch.tensor([1.0,2.0,3.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor

tensor([1., 2., 3.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.])

In [24]:
four_dimention_tesor=torch.rand(4,5,6,7)
print(four_dimention_tesor)

tensor([[[[9.3123e-01, 1.3840e-01, 3.6953e-01, 3.7261e-01, 8.2094e-01,
           7.2647e-01, 8.2672e-01],
          [3.7868e-01, 8.9268e-01, 8.9600e-01, 8.3244e-01, 8.9835e-01,
           7.3443e-01, 9.7026e-01],
          [9.5104e-01, 6.2958e-01, 6.1556e-01, 3.0867e-01, 6.8142e-01,
           6.8003e-01, 1.4473e-01],
          [9.6743e-01, 1.9610e-01, 4.9623e-02, 9.2315e-02, 6.5201e-01,
           2.9891e-01, 7.8114e-02],
          [4.0820e-01, 7.1524e-02, 8.6083e-01, 9.2668e-02, 4.8212e-02,
           4.6808e-01, 1.7158e-01],
          [1.4990e-01, 5.5666e-02, 1.7938e-01, 7.6592e-01, 1.2726e-04,
           9.4631e-01, 8.7242e-01]],

         [[4.7317e-01, 3.1668e-01, 9.1256e-01, 9.1202e-01, 1.9535e-01,
           3.9465e-01, 4.3547e-01],
          [7.0479e-01, 1.6735e-02, 8.3460e-01, 5.1943e-01, 1.3970e-01,
           1.3791e-02, 2.1792e-01],
          [1.7971e-01, 5.2598e-01, 1.0978e-01, 4.7437e-01, 9.4349e-02,
           3.9404e-01, 6.9651e-01],
          [4.6643e-01, 2.0329e-01, 

###Tensors operations

In [25]:
tensor=torch.tensor([1,2,3])
tensor+1

tensor([2, 3, 4])

In [26]:
(tensor+1)*(5+5)

tensor([20, 30, 40])

In [27]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.1 ms, sys: 15 µs, total: 1.12 ms
Wall time: 15.3 ms


tensor(14)

In [28]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.33 ms, sys: 765 µs, total: 2.1 ms
Wall time: 2.36 ms


In [29]:
matrix_multi=torch.matmul(torch.rand(3,2), torch.rand(2,3))
print(matrix_multi)

tensor([[1.4957, 0.3739, 1.4697],
        [0.4723, 0.1182, 0.4498],
        [0.8853, 0.2213, 0.8678]])


In [31]:
mean_=torch.arange(0,100,8)
print(mean_)
mean_.dtype

tensor([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96])


torch.int64

In [32]:
mean_.min(),torch.min(mean_)

(tensor(0), tensor(0))

In [33]:
torch.max(mean_)

tensor(96)

In [34]:
mean_.max()

tensor(96)

In [35]:
torch.mean(mean_.type(torch.float32))

tensor(48.)

In [36]:
mean_.argmax()

tensor(12)

In [37]:
mean_.mode()

torch.return_types.mode(
values=tensor(0),
indices=tensor(0))

In [38]:
mean_.median()

tensor(48)

In [39]:
x=torch.arange(1,13,1)
print({x})

{tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])}


In [40]:
x.shape

torch.Size([12])

In [41]:
x.ndim

1

In [42]:
x.ndim

1

In [43]:
x_reshaping=x.reshape(2,2,3)
print(x_reshaping)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [44]:
x.view(2,3,2)

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [45]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
z=x.view(1,12)
print(z)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [51]:
z[:,0]=3
z

tensor([[ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
x_stacked=torch.stack([x,x,x],dim=0)
print(x_stacked)

tensor([[ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 3,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])


In [53]:
x=torch.arange(1,10,1).reshape(3,3,1)
print(x)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])


In [54]:
x[2][1]

tensor([8])

In [57]:
x=torch.arange(1,18,2).reshape(1,3,3)
print(x)

tensor([[[ 1,  3,  5],
         [ 7,  9, 11],
         [13, 15, 17]]])


In [75]:
x[0]

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]])