<a href="https://colab.research.google.com/github/Mohittrathee/Mullitiple_disease_prediction-using-ml/blob/main/pytorch2_and_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import torch

In [3]:
array=np.arange(1,10)
tensor=torch.from_numpy(array)
print(array)
print(tensor)

[1 2 3 4 5 6 7 8 9]
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
array.dtype,tensor.dtype

(dtype('int64'), torch.int64)

In [5]:
tensor.type(torch.float32)
tensor.dtype

torch.int64

In [6]:
tensor=torch.ones(9)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
tensor=torch.randint(1,10,(3,3))
tensor

tensor([[8, 6, 6],
        [1, 1, 7],
        [1, 2, 2]])

In [8]:
tensor_A=torch.rand(3,3)
tensor_B=torch.rand(3,3)
print(tensor_A,tensor_B)
print(tensor_A==tensor_B)

tensor([[0.3590, 0.2833, 0.4433],
        [0.1677, 0.4509, 0.8245],
        [0.1715, 0.1853, 0.2054]]) tensor([[0.5100, 0.6429, 0.2997],
        [0.1285, 0.2538, 0.1853],
        [0.1338, 0.8212, 0.6094]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [9]:
RANDOM_SEED=32
torch.manual_seed(RANDOM_SEED)
tensor_C=torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
tensor_D=torch.rand(3,3)
print(tensor_C, tensor_D)
print(tensor_C==tensor_D)

tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793],
        [0.6481, 0.0229, 0.5874]]) tensor([[0.8757, 0.2721, 0.4141],
        [0.7857, 0.1130, 0.5793],
        [0.6481, 0.0229, 0.5874]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [10]:
torch.cuda.is_available()

True

In [11]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [12]:
tensor=torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [14]:
random_tensor=torch.rand(7,7)
print(random_tensor)

tensor([[0.5589, 0.4112, 0.9977, 0.5187, 0.9310, 0.2028, 0.6240],
        [0.4142, 0.9531, 0.6668, 0.5360, 0.1804, 0.0755, 0.3405],
        [0.7576, 0.2296, 0.2900, 0.0625, 0.9716, 0.9518, 0.2123],
        [0.5161, 0.4722, 0.5887, 0.1751, 0.1881, 0.4266, 0.1156],
        [0.5557, 0.2444, 0.1048, 0.4753, 0.2905, 0.7066, 0.9065],
        [0.2047, 0.3438, 0.4117, 0.0127, 0.0150, 0.6994, 0.4675],
        [0.2444, 0.9778, 0.0017, 0.9419, 0.0226, 0.2056, 0.7737]])


In [15]:
tensor_2=torch.rand(1,7)
print(tensor_2)

tensor([[0.3734, 0.3499, 0.1588, 0.6527, 0.9031, 0.6629, 0.9895]])


In [16]:
tensor_3=torch.rand(1,7)
print(tensor_3)

tensor([[0.1029, 0.0882, 0.2003, 0.4493, 0.5874, 0.5102, 0.5595]])


In [17]:
matrix_multi=torch.matmul(tensor_2,tensor_3.T)
print(matrix_multi)

tensor([[1.8167]])


In [19]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
tensor_2=torch.rand(1,7)

torch.manual_seed(RANDOM_SEED)
tensor_3=torch.rand(1,7)

print(tensor_2)
print(tensor_3)
print(tensor_2==tensor_3)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[True, True, True, True, True, True, True]])


In [21]:
RANDOM_SEED=1234
torch.manual_seed(RANDOM_SEED)
x=torch.rand(2,3)
torch.manual_seed(RANDOM_SEED)
y=torch.rand(2,3)
print(x)
print(y)

device="cuda"if torch.cuda.is_available() else "cpu"
print(device)
x=x.to(device)
y=y.to(device)
print(x)
print(y)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')


In [22]:
mul=torch.matmul(x,y.T)
print(mul)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')


In [23]:
mul.argmax()

tensor(3, device='cuda:0')

In [24]:
mul.argmin()

tensor(1, device='cuda:0')

In [25]:
mul.max()

tensor(0.6287, device='cuda:0')

In [26]:
mul.min()

tensor(0.2161, device='cuda:0')

In [28]:
z=torch.rand(1,1,1,10)
print(z)
z.squeeze()

tensor([[[[0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294,
           0.9665, 0.7399]]]])


tensor([0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665,
        0.7399])